### ISSUE TITLE
Support enabling features via a module

### ISSUE THREAD

**Issue by mikeycmccarthy** [citrix/netscaler-ansible-modules#18]
It'd be great to be able to enable (or disable) features using a module. We need to turn compression on as a feature and it'd be good not to revert to the API if possible.

**Comment by giorgos-nikolopoulos** [comment]
@mikeycmccarthy  apologies for the delayed answer.

Currently we do not have a module for the specific task of enabling features.

I would suggest to use the generic nitro request module to perform the enabling or disabling of features.

A sample playbook that enables the compression feature can be found [here](https://github.com/citrix/netscaler-ansible-modules/blob/master/samples/nitro_request/enable_feature.yaml).

**Comment by mikeycmccarthy** [comment]
Thanks, much appreciated.
