### ISSUE TITLE
Does graceful option need a wait time?

### ISSUE THREAD

**Issue by brucejfreeman** [citrix/netscaler-ansible-modules#25]
From https://docs.citrix.com/en-us/netscaler/10-5/ns-tmg-wrapper-10-con/ns-lb-wrapper-con-10/ns-lb-clienttraffic-con/ns-lb-clienttraffic-gracefulshutdown-tsk.html it seems like if graceful is yes but no wait time is given then the load balancer will wait until the last connection is serviced no matter how long that takes.

There should be the option to give a wait time so that the first case in the table in the link above could be handled. We've used the wait_time feature from https://github.com/ansible/ansible-modules-extras/pull/2327 to make sure servers are removed from the load balancer even if they have long running connections.

Does this parameter need to be added to this module as well?

Thanks

**Comment by giorgos-nikolopoulos** [comment]
The delay option that was added is the nitro object attribute that corresponds to the "wait time" mentioned in the [referenced article](https://docs.citrix.com/en-us/netscaler/10-5/ns-tmg-wrapper-10-con/ns-lb-wrapper-con-10/ns-lb-clienttraffic-con/ns-lb-clienttraffic-gracefulshutdown-tsk.html).
