### ISSUE TITLE
SSL cert key linking support

### ISSUE THREAD

**Issue by mikeycmccarthy** [citrix/netscaler-ansible-modules#53]
It'd be great to have ssl cert key linking support (ie. what turns up in a show run as 'link ssl certKey etc') - there is some code that relates to 'linkcertkeyname' but seems like it isn't supported as a module argument.

Thanks!

**Comment by giorgos-nikolopoulos** [comment]
@mikeycmccarthy 
Closing this issue as it is quite old.

If you still have this particular issue please re raise it in as a new issue.
