### ISSUE TITLE
imperative style configuration 

### ISSUE THREAD

**Issue by chiradeep** [citrix/netscaler-ansible-modules#56]
Currently modules are usually declarative - you specify the desired state and the Ansible module will converge to it by automatically adding and removing resources to move the current state to the desired state. 
This is not always desirable, sometimes you have resources defined outside Ansible that you want to modify. For example, if there is a service group with 5 members and you want to add 3 members to it, currently Ansible will delete the 5 previous members first and add only 3 members.

**Comment by giorgos-nikolopoulos** [comment]
The newer Citrix ADC modules ( all citrix_adc_appfw_*) have three options for how to implement the bindings addition/deletion.
This is controlled by the option `mode` which can have three values `exact`, `bind`, `unbind`.

In short `exact` is the behavior that exists right now. Delete existing but undefined bindings, add missing bindings and modify differing existing bindings.

With `bind` every task configured binding is either added if it is not already present or modified if it exists with different parameters.

With `unbind` every task configured binding is removed if it exists.

See the documentation of the `citrix_adc_appfw_profile` for more [details](https://netscaler-ansible.readthedocs.io/en/latest/modules/citrix_adc_appfw_profile_module.html#citrix-adc-appfw-profile-module)

For older modules we will need to rewrite them to implement this fucntionality.

I will close this issue and keep track of this feature request as an issue on our internal Jira.
