### ISSUE TITLE
sslv3, tls 1.0 and tls 1.1 disable using ansible

### ISSUE THREAD

**Issue by pavankalyanvskp** [citrix/netscaler-ansible-modules#64]
I am finding it difficult to find the module to disable sslv3, tls 1.0 and tls 1.1 settings on the ssl vserver.

**Comment by sumanth-lingappa** [comment]
Hi @pavankalyanvskp , can you please elaborate the issue you are facing?

**Comment by giorgos-nikolopoulos** [comment]
Unfortunately the ssl configuration options are not supported in the current implementation of `citrix_adc_lb_vserver` and `citrix_adc_cs_vserver`.

We will be adding this functionality when we revisit the implementation of these modules.

For now there are two solutions to the problem of enabling/disabling the ssl option for a target ssl vserver.
* Use `citrix_adc_nitro_request` with the `sslvserver` NITRO object to set the appropriate options.
* Use the standard Ansible `shell` module along with the `ssh_citrix_adc` connection plugin to issue the appropriate `nscli` commands

I will detail both solutions.
### Using `citrix_adc_nitro_request`

We will be updating the appropriate attributes of the `sslvserver` NITRO object.
The full documentation for this object can be found [here](https://developer-docs.citrix.com/projects/netscaler-nitro-api/en/latest/configuration/ssl/sslvserver/sslvserver/)

First we need to identify the exact attribute name we need.
This can be done by going over the documentation or using the following playbook, which will print all the attributes that can be retrieved from the target ssl vserver.

```

- hosts: citrix_adc
  gather_facts: False


  tasks:

    - name: Get ssl vserver
      delegate_to: localhost
      register: get_result
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        operation: get

        resource: sslvserver
        name: 'test_ssl_cs_vserver'

    - name: Show sslvserver NITRO object
      debug:
        msg: "{{ get_result.nitro_object }}"
```
The output of the `debug` task will be something like the following
```
TASK [Show sslvserver NITRO object] ***************************************************************************************************************************
ok: [citrix_adc_vpx121] => {
    "msg": [
        {
            "ca": false,
            "cipherredirect": "DISABLED",
            "cleartextport": 0,
            "clientauth": "DISABLED",
            "dh": "DISABLED",
            "dhcount": "0",
            "dhekeyexchangewithpsk": "NO",
            "dhkeyexpsizelimit": "DISABLED",
            "dtlsflag": false,
            "ersa": "ENABLED",
            "ersacount": "0",
            "hsts": "DISABLED",
            "includesubdomains": "NO",
            "invoke": false,
            "maxage": "0",
            "nonfipsciphers": "DISABLED",
            "ocspstapling": "DISABLED",
            "polinherit": "0",
            "priority": "0",
            "pushenctrigger": "Always",
            "redirectportrewrite": "DISABLED",
            "sendclosenotify": "YES",
            "service": "0",
            "sessreuse": "ENABLED",
            "sesstimeout": "120",
            "skipcaname": false,
            "snicert": false,
            "snienable": "DISABLED",
            "ssl2": "DISABLED",
            "ssl3": "ENABLED",
            "sslredirect": "DISABLED",
            "sslv2redirect": "DISABLED",
            "strictsigdigestcheck": "DISABLED",
            "tls1": "DISABLED",
            "tls11": "DISABLED",
            "tls12": "ENABLED",
            "tls13": "DISABLED",
            "tls13sessionticketsperauthcontext": "1",
            "vservername": "test_ssl_cs_vserver",
            "zerorttearlydata": "DISABLED"
        }
    ]
}

```
Then it is a matter of identifying the attribute we want changed and using the `citrix_adc_nitro_request` module to update this particular attribute or set of attributes we are interested in.

For example if we wanted to change just the `tls1` attribute we would use the following playbook.
```
    - name: Update ssl cert
      delegate_to: localhost
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        operation: update

        resource: sslvserver
        name: 'test_ssl_cs_vserver'
        attributes:
          vservername: "test_ssl_cs_vserver"
          tls1: "DISABLED"
```

### Using the standard Ansible `shell` module and `ssh_citrix_adc` connection plugin to issue `nscli` commands.

This method is very simple. It just requires us to issue the `nscli` commands through the playbook.
Please refer to the connection plugin [documentation](https://github.com/citrix/netscaler-ansible-modules#citrix-adc-connection-plugin) to make sure your environment is set up to correctly for the plugin to work.

For setting an `sslvserver` option the following playbook could be used

```
- hosts: citrix_adc
  remote_user: nsroot
  connection: ssh_citrix_adc
  gather_facts: False
  vars:
    ansible_python_interpreter: /var/python/bin/python

  tasks:
    - name: Set ssl vserver option
      shell: nscli -s -U :nsroot:nsroot "set ssl vserver test_ssl_cs_vserver -tls1 ENABLED"
      register: nscli_output

    - name: Show nscli output
      debug:
        msg: "{{ nscli_output }}"
```
For setting multiple ssl options multiple `shell` tasks must be used.

I hope this helps you out. If you have any further issues please re raise the issue.

**Comment by Haykeenz** [comment]
can someone please help me with an ansible playbook module to disable tls 1.0, 1.1 and Enable tls 1.2 on CentOS. Thank you
