### ISSUE TITLE
Question: Is there a ansible_module which can be used to configure the netscaler firewall?

### ISSUE THREAD

**Issue by sanket4373** [citrix/netscaler-ansible-modules#7]
So far I have used the ansible plays in this repo to create servicegroups and Load Balancer (VServer). I was going through the `yml` files to look for any firewall configuration related ansible_module, did not find any.

I am trying to do whitelisting of incoming traffic from certain IP's to the netscaler using the below shown command and I wanted to automate this process as well. Is there an ansible_module already implemented to achieve this or will I have to write one from scratch to do so?

```
add ns acl allow-jenkins-management ALLOW -srcIP = xxx.xxx.xxx.xx -destIP = xxx.xxx.xxx.xx -priority 90 -kernelstate SFAPPLIED61
```

**Comment by giorgos-nikolopoulos** [comment]
Unfortunately currently we do not have a module for configuring the NS firewall.

At this point we are focused on the modules that are relevant to the most often changing configuration elements of Netscaler.

A workaround could be to use the `command` module to issue the cli command or use the `template` module to upload an updated ns.conf.

If you find you  have the time, you could use the current modules and the utility scripts to implement such a module.

Take a look at the [developer documentation](http://netscaler-ansible.readthedocs.io/en/latest/development/development-utilities.html) for the modules. It is somewhat sparse at the moment but it's better than starting from scratch. 

Also we would be glad to help you for any further questions you may have.

**Comment by giorgos-nikolopoulos** [comment]
We did some work on configuring netscaler with generic Ansible modules.

Have a look at the following links.

http://netscaler-ansible.readthedocs.io/en/latest/generic_modules/template_ns_conf.html
http://netscaler-ansible.readthedocs.io/en/latest/generic_modules/nitro_api_calls.html
