### ISSUE TITLE
Unable to Perform Simple Disable Service Group Operation

### ISSUE THREAD

**Issue by MrBones757** [citrix/netscaler-ansible-modules#76]
The citrix_adc_servicegroup module does not appear to allow you to disable the sg without providing a heap of other parameters.

I am trying to convert Powershell scripts (Enable-NSServiceGroup cmdlet) to these ansible modules for plays.
It appears that every time the module runs, it resets the netscaler to the configuration of the module call rather than simply toggling the enable / disable & graceful functionality.

I have tried to use the citrix_adc_nitro_request module to achieve this though functionality seems to be the same result.

Examples of module invocations:
name: Do a Thing
 netscaler_nitro_request:
   nitro_protocol: https
   nitro_user: "{{ im_ad_username }}"
   nitro_pass: "{{ im_ad_password }}"
   nsip: "{{ im_netscaler_dict[im_netscaler_sg_name]['im_netscaler_ip'] }}"
   validate_certs: no
   operation: "action"
   action: "disable"
   attributes:
     servicegroupname: "{{ im_netscaler_sg_name }}"
     graceful: "yes"
   resource: servicegroup
 register: result_sg

- name: Do another thing
citrix_adc_servicegroup :
   nitro_protocol: https
   nitro_user: "{{ im_ad_username }}"
   nitro_pass: "{{ im_ad_password }}"
   nsip: "{{ im_netscaler_dict[im_netscaler_sg_name]['im_netscaler_ip'] }}"
   validate_certs: no
   servicegroupname: "{{ im_netscaler_sg_name }}"
   disabled: yes
   graceful: "yes"
   state: present

Any information on how to achieve this functionality would be appreciated. It can be done though the UI  and Powershell so i assume its doable using Ansible too.

**Comment by sumanth-lingappa** [comment]
Hello @MrBones757 , thank you for raising this issue. We will get back once analyzing this.
Thank you.

**Comment by MrBones757** [comment]
I might add that i have tried using the netscaler_* modules included with ansible and citrix_* modules from this repo with the same issue occuring in both scenarios.

**Comment by sumanth-lingappa** [comment]
Noted.

**Comment by MrBones757** [comment]
Just wondering if there was any update on this & if you were able to reproduce issues.

**Comment by sumanth-lingappa** [comment]
@MrBones757 The scenario is perfectly working: Please find below two ways to achieve this. Revert for any.

	- hosts: citrix_adc

	  vars:
		max_clients: 5

	  remote_user: root
	  gather_facts: False

	  tasks:
		- name: Disable service group
		  delegate_to: localhost
		  citrix_adc_servicegroup:
			nsip: "{{ nsip }}"
			nitro_user: "{{ nitro_user }}"
			nitro_pass: "{{ nitro_pass }}"

			state: present

			servicegroupname: test_svcgrp
			disabled: yes

OR

	- hosts: citrix_adc
	  gather_facts: no

	  tasks:
		- name: Get resource
		  delegate_to: localhost
		  register: result
		  citrix_adc_nitro_request:
			nsip: "{{ nsip }}"
			nitro_user: "{{ nitro_user }}"
			nitro_pass: "{{ nitro_pass }}"

			operation: action
			action: disable

			resource: servicegroup
			attributes:
			  servicegroupname: test_svcgrp

**Comment by MrBones757** [comment]
Hello,
Sorry for my slow reply.
I have re-verified this configuration and i am still not seeing this functioning. I have made sure i am using the most up to date version of the modules from this repo. Ansible verison is 2.7.5
The configuration used was:

- name: set_state | Toggle new connections to {{ im_netscaler_sg_name }}
  citrix_adc_servicegroup:
    nsip: "{{ ns_ip }}"
    nitro_user: "{{ im_ad_username }}"
    nitro_pass: "{{ im_ad_password }}"
    state: present
    servicegroupname: "{{ im_netscaler_sg_name }}"
    disabled: yes
    validate_certs: no
    nitro_protocol: "https"
  register: result_sg
  delegate_to: localhost

Before:
![disable_before](https://user-images.githubusercontent.com/22608473/53323958-854f2400-391a-11e9-81cc-c98051ed7b29.PNG)

After:
![disable_after](https://user-images.githubusercontent.com/22608473/53323957-854f2400-391a-11e9-9215-a5785f6aaf71.PNG)

Job Output:
{
    "nitro_severity": "NONE",
    "_ansible_parsed": true,
    "_ansible_no_log": false,
    "http_response_body": "{ \"errorcode\": 0, \"message\": \"Done\", \"severity\": \"NONE\", \"servicegroup\": [ { \"servicegroupname\": \"<redacted>\", \"numofconnections\": 0, \"servicetype\": \"TCP\", \"port\": 0, \"td\": \"0\", \"serviceconftype\": true, \"cachetype\": \"SERVER\", \"maxclient\": \"0\", \"maxreq\": \"0\", \"cacheable\": \"NO\", \"cip\": \"DISABLED\", \"usip\": \"NO\", \"pathmonitor\": \"NO\", \"pathmonitorindv\": \"NO\", \"useproxyport\": \"YES\", \"monweight\": \"0\", \"sc\": \"OFF\", \"sp\": \"OFF\", \"rtspsessionidremap\": \"OFF\", \"clttimeout\": 9000, \"svrtimeout\": 9000, \"cka\": \"NO\", \"tcpb\": \"NO\", \"cmp\": \"NO\", \"maxbandwidth\": \"0\", \"state\": \"ENABLED\", \"svrstate\": \"DOWN\", \"delay\": 0, \"ip\": \"0.0.0.0\", \"monthreshold\": \"0\", \"monstate\": \"ENABLED\", \"monitor_state\": \"Unknown\", \"monstatcode\": 0, \"monstatparam1\": 0, \"monstatparam2\": 0, \"monstatparam3\": 0, \"monitortotalprobes\": \"0\", \"monitortotalfailedprobes\": \"0\", \"monitorcurrentfailedprobes\": \"0\", \"downstateflush\": \"ENABLED\", \"statechangetimesec\": \"Mon Feb 25 05:56:47 2019\", \"statechangetimemsec\": \"933\", \"tickssincelaststatechange\": \"882441\", \"stateupdatereason\": \"0\", \"clmonowner\": \"4294967295\", \"clmonview\": \"0\", \"groupcount\": \"0\", \"comment\": \"<redacted>", \"hashid\": \"0\", \"riseapbrstatsmsgcode\": 0, \"riseapbrstatsmsgcode2\": 1, \"graceful\": \"NO\", \"healthmonitor\": \"YES\", \"appflowlog\": \"ENABLED\", \"autoscale\": \"DISABLED\", \"memberport\": 0, \"serviceipstr\": \"0.0.0.0\", \"passive\": false, \"servicegroupeffectivestate\": \"UP\", \"monconnectionclose\": \"NONE\" } ] }",
    "_ansible_delegated_vars": {
        "ansible_delegated_host": "localhost",
        "ansible_host": "localhost"
    },
    "nitro_message": "Done",
    "changed": false,
    "nitro_errorcode": 0,
    "http_response_data": {
        "status": 200,
        "content-length": "1484",
        "url": "https://<redacted>/nitro/v1/config/servicegroup/<redacted>",
        "expires": "Thu, 19 Nov 1981 08:52:00 GMT",
        "cookies": {},
        "server": "Apache",
        "msg": "OK (1484 bytes)",
        "connection": "close",
        "pragma": "no-cache",
        "cache-control": "no-store, no-cache, must-revalidate, post-check=0, pre-check=0",
        "date": "Mon, 25 Feb 2019 08:23:52 GMT",
        "content-type": "application/json; charset=utf-8",
        "cookies_string": ""
    },
    "invocation": {
        "module_args": {
            "instance_id": null,
            "instance_ip": null,
            "resource": "servicegroup",
            "name": "<redacted>",
            "expected_nitro_errorcode": [
                0,
                258
            ],
            "validate_certs": false,
            "args": null,
            "filter": null,
            "nitro_protocol": "https",
            "nsip": "<redacted>",
            "nitro_user": "tabsvrad",
            "action": null,
            "attributes": null,
            "nitro_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "instance_name": null,
            "operation": "get",
            "nitro_auth_token": null
        }
    },
    "nitro_object": [
        {
            "comment": "<redacted>",
            "tcpb": "NO",
            "monweight": "0",
            "ip": "0.0.0.0",
            "riseapbrstatsmsgcode2": 1,
            "maxreq": "0",
            "maxbandwidth": "0",
            "statechangetimesec": "Mon Feb 25 05:56:47 2019",
            "svrtimeout": 9000,
            "cachetype": "SERVER",
            "port": 0,
            "clttimeout": 9000,
            "passive": false,
            "servicetype": "TCP",
            "serviceipstr": "0.0.0.0",
            "clmonowner": "4294967295",
            "maxclient": "0",
            "servicegroupname": "<redacted>",
            "groupcount": "0",
            "monitorcurrentfailedprobes": "0",
            "delay": 0,
            "state": "ENABLED",
            "usip": "NO",
            "monstate": "ENABLED",
            "graceful": "NO",
            "rtspsessionidremap": "OFF",
            "td": "0",
            "autoscale": "DISABLED",
            "pathmonitorindv": "NO",
            "pathmonitor": "NO",
            "appflowlog": "ENABLED",
            "monitor_state": "Unknown",
            "riseapbrstatsmsgcode": 0,
            "svrstate": "DOWN",
            "tickssincelaststatechange": "882441",
            "cacheable": "NO",
            "monstatcode": 0,
            "monitortotalprobes": "0",
            "servicegroupeffectivestate": "UP",
            "serviceconftype": true,
            "hashid": "0",
            "numofconnections": 0,
            "monitortotalfailedprobes": "0",
            "cka": "NO",
            "monstatparam1": 0,
            "monstatparam2": 0,
            "monconnectionclose": "NONE",
            "stateupdatereason": "0",
            "sp": "OFF",
            "downstateflush": "ENABLED",
            "statechangetimemsec": "933",
            "cip": "DISABLED",
            "healthmonitor": "YES",
            "useproxyport": "YES",
            "sc": "OFF",
            "memberport": 0,
            "monstatparam3": 0,
            "clmonview": "0",
            "monthreshold": "0",
            "cmp": "NO"
        }
    ]
}

Note all server and monitor configuration has disappeared.
Netscaler vpx version: NS11.1 58.13.nc

**Comment by sumanth-lingappa** [comment]
@MrBones757 , please allow me couple of days to revert back on this.

**Comment by giorgos-nikolopoulos** [comment]
@MrBones757 
We recently added the `ssh_citrix_adc` connection plugin which allows you to use standard Ansbile modules with Citrix ADC.

With the use of the `shell` Ansible module you can issue `nscli` commands.
Disabling or enabling a servicegroup could be accomplished with the following playbooks

Disabling: 
```
- hosts: citrix_adc
  remote_user: nsroot
  connection: ssh_citrix_adc
  gather_facts: False
  vars:
    ansible_python_interpreter: /var/python/bin/python

  tasks:
    - name: Disable servicegroup test_service_group
      shell: nscli -s -U :nsroot:nsroot "disable servicegroup test_service_group"
      register: nscli_output

    - name: Show nscli output
      debug:
        msg: "{{ nscli_output }}"
```

Enabling.
```- hosts: citrix_adc
  remote_user: nsroot
  connection: ssh_citrix_adc
  gather_facts: False
  vars:
    ansible_python_interpreter: /var/python/bin/python

  tasks:
    - name: Enable servicegroup test_service_group
      shell: nscli -s -U :nsroot:nsroot "enable servicegroup test_service_group"
      register: nscli_output

    - name: Show nscli output
      debug:
        msg: "{{ nscli_output }}"
```

Make sure you have setup the connection plugin correctly as is detailed in this [section](https://github.com/citrix/netscaler-ansible-modules#citrix-adc-connection-plugin) of the README file.

Let us know if this works out for you.

**Comment by MrBones757** [comment]
Apologies for the slow reply.
Unfortunately this solution does not work in the setup implemented as we are using AD/LDAP logins to control access and permissions via the API/UI rather than directly accessing the command-line of the VPX instance.
I have done some research and found an alternative to the standard modules which use API calls to trigger actions on the netscaler. Using these i was able to create my own temporary solution to this issue until the underlying issue (?) with the provided modules can be determined.

**Comment by giorgos-nikolopoulos** [comment]
Since you cannot access the `nscli` I see the proposed solution cannot work.

Another alternative that skipped my mind is to use the `citrix_adc_nitro_request` module to enable/disable the target servicegroup.

Here is a sample playbook that disables the `test_service_group`

```
- hosts: citrix_adc
  gather_facts: False
  vars:
  tasks:
    - name: Add Service
      delegate_to: localhost
      register: result
      netscaler_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        operation: action
        action: disable
        resource: servicegroup
        attributes:
          servicegroupname: "test_service_group"
```

To enable the servicegroup use the same playbook with `action: enable`

We will be tracking this issue in our internal Jira to make sure we address this when we rewrite the servicegroup module.
