### ISSUE TITLE
citrix_adc_service syntax documentation error

### ISSUE THREAD

**Issue by padavrexi** [citrix/netscaler-ansible-modules#77]
[Documentation example for citrix_adc_service.py](https://github.com/citrix/netscaler-ansible-modules/blob/master/docs/modules/citrix_adc_service_module.rst) states the following syntax for monitor_bindings:
```
monitor_bindings:
  - monitor-1
```
whereas it should be:
```
monitor_bindings:
  - monitorname: monitor-1
```

**Comment by sumanth-lingappa** [comment]
@padavrexi Thank you for the opening the issue. This is resolved now.
